version: "3.8"

services:
  postgres:
    container_name: postgres_sitforms
    image: library/postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sitformsdb
    ports:
      - "9000:5432"
    restart: unless-stopped

#  react:
#    container_name: react
#    build: .
#    ports:
#      - "3000:3000"